defaults:
  - _self_
  - problem: trajectory_prediction
  - llm_client: openai
  # [Optional] set different clients for operators
  - llm_client@llm_long_ref: null
  - llm_client@llm_short_ref: null
  - llm_client@llm_crossover: null
  - llm_client@llm_mutation: null
  - override hydra/output: local
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    name: ${problem.problem_name}-${problem.problem_type}
    chdir: True

# The chosen algorithm
algorithm: trajevo

# Main GA loop parameters
max_fe: 100 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 30 # initial population size for GA
mutation_rate: 0.5 # mutation rate for GA
timeout: 20 # timeout for evaluation of a single heuristic
diversify_init_pop: True # whether to diversify the initial population
restart_threshold: 6  # restart if no improvement in this many generations
restart_diversity: 0.5  # regenerate 50% population
improvement_threshold: 1e-2  # restart if improvement is below this value
wandb_project: "trajevo"
wandb_name: null
use_wandb: True
num_processes: 16 # number of processes to use for parallel evaluation
seed: 0
